development:
  adapter: postgresql
  encoding: unicode
  database: users
  pool: 5
  host: localhost
  username: postgres
  password: dagsdags13

test:
  adapter: postgresql
  encoding: unicode
  database: test_users
  pool: 5
  username: postgres
  password: dagsdags13

staging:
  url: <% ENV['DATABASE_URL'] %>

production:
  url: <% ENV['DATABASE_URL'] %>
